apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-pv
spec:
    capacity:
        storage: 15Gi
    accessModes:
        - ReadWriteMany
    storageClassName: nfs
    nfs:
        path: /exports
        server: 35.244.48.208
