services:
    postgres:
        image: postgres
        container_name: postgresdb
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=mysecretpassword

    backend:
        build:
            network: host
            context: ./
            dockerfile: Dockerfile

        environment:
            - DATABASE_URL=postgresql://postgres:mysecretpassword@postgresdb:5432/postgres

        ports:
            - "3000:3000"
        depends_on:
            - postgres
volumes:
    postgres_data:
